### ISSUE TITLE
PyTorch Model Not Utilizing GPU Defaulting to CPU

### ISSUE THREAD

**Issue by sadhanadhanukonda** [Infosys/Infosys-Model-Inference-Library#2]
I am experiencing an issue where my PyTorch model is not utilizing the available GPU resources and instead running only on the CPU. Despite having compatible GPU installed and the necessary drivers up-to-date, the model is not leveraging the GPU's acceleration capabilities.

**Troubleshoot steps that i have done:**
1. Verified GPU installation and drivers
2. Checked PyTorch version and CUDA compatibility
3. Attempted to manually set the device as CUDA in the mil_config.json.

**Actual Behavior:** The Model is running on CPU, resulting in slower computation times.

**Request:**
I'd appreciate assistance in resolving the issue and ensuring the Model utilizes the GPU resources as expected.

**Comment by tarunsk1998** [comment]
Hi @sadhanadhanukonda, This issue has been resolved as part of the latest commit.
https://github.com/Infosys/Infosys-Model-Inference-Library/commit/d96bd461cee8e93826e879ec9dc0545a32664788
Please let us know if you are still facing the issue.
